### ISSUE TITLE
DeviceNotReadyException: Device is not connected

### ISSUE THREAD

**Issue by AntoineDuret** [rwalle/py_thorlabs_ctrl#2]
Hello,

I am trying to use your project with a KDC101 controller and MTS50M-Z8 stage. The controller's serial number is 27263558.
When executing the following lines of code:

import py_thorlabs_ctrl.kinesis
py_thorlabs_ctrl.kinesis.init(r'C:\Program Files\Thorlabs\Kinesis') 
from py_thorlabs_ctrl.kinesis.motor import KCubeDCServo
tcube = KCubeDCServo(27263558)
tcube.create()
tcube.enable()

I only have an exception coming from the enable() call, itself coming from the motor.py file at line 48:
device.Connect(self.serial_number)

DeviceNotReadyException: Device is not connected
   à Thorlabs.MotionControl.DeviceManagerCLI.ThorlabsGenericCoreDeviceCLI.VerifyDeviceConnected(Int32 functionDepth)
   à Thorlabs.MotionControl.GenericMotorCLI.GenericMotorCLI.Connect(String serialNo)

The problem is that I do not understand this exception, as my device is connected and powered on, I can control it with the Kinesis software, and the correct serial number is used.

Do you know how to fix this issue?

Many thanks in advance!

Best regards,

Antoine

**Comment by rwalle** [comment]
Hi,

It has been a long while since I worked in a lab, so I do not remember a lot of details. I have probably run into this situation before, but cannot recall what triggered it and how I resolved it. It is likely related to how it works with Kinesis -- for example, you cannot have Kinesis controlling the same motor at the same time, and you may need to explicitly disconnect the device from the Kinesis panel. (I vaguely remember that there is a button that allows you to do it.) If none of these work, there is a small chance that Thorlabs has changed their API, and you would need to either use an older version of Kinesis or modify the code in this package yourself. That is as much insight as I can offer here.

**Comment by AntoineDuret** [comment]
Thanks for your rapid answer!
You were right, the Kinesis software shall not be connected to the device when using the code. And I have to disconnect the device before closing or restarting the code, as you do in the example.
Best,
Antoine
